version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: schoolcrm
      POSTGRES_USER: schoolcrm
      POSTGRES_PASSWORD: schoolcrm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
    build: .
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=schoolcrm
      - DJANGO_DB_USER=schoolcrm
      - DJANGO_DB_PASSWORD=schoolcrm
volumes:
  postgres_data: 